config/routes.rb
TwilightStruggle::Application.routes.draw do

  resources :trackers

  resources :country_scores

  resources :games

  resources :regions

  resources :countries

  devise_for :users, controllers: { registrations: 'registrations' }

  devise_scope :user do
    get '/login' => 'devise/sessions#new', as: :login
    get '/logout' => 'sessions#destroy', :as => :logout
    get '/signup' => 'registrations#new', :as => :signup
    scope 'my' do
      get 'profile', to: 'registrations#edit'
      put 'profile/update', to: 'registrations#update'
      get 'password/edit', to: 'registrations#edit_password'
      put 'password/update', to: 'registrations#update_password'
    end
  end

  unauthenticated do
    get '/logout' => redirect('/')
  end

  authenticate :user, ->(u) { u.super_admin? } do
    get '/delayed_job' => DelayedJobWeb, :anchor => false
    put '/delayed_job' => DelayedJobWeb, :anchor => false
    post '/delayed_job' => DelayedJobWeb, :anchor => false

    ActiveAdmin.routes(self)
    namespace :superadmin do
      root to: 'users#index'
      resources :users
    end

  end

  get 'pages/about'
  get 'pages/contact_us'
  resources :contacts, only: [:create]

  authenticated :user do
    get '/pages' => 'pages#index', as: :pages
  end

  unauthenticated do
    as :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_scope :user do
        post 'login' => 'sessions#create', as: 'login'
      end

      resources :users, only: [:show, :create, :update, :destroy], constraints: { id: /.*/ }
    end
  end

  root 'home#index'
end

app/models/card.rb
class Card < ActiveRecord::Base

end

app/models/connection.rb
class Connection < ActiveRecord::Base

  belongs_to :country
  belongs_to :neighbor, class_name: "Country"

end

app/models/contact.rb
class Contact
  include ActiveModel::Model

  attr_accessor :email, :title, :body

  validates :email, :title, presence: true
  validates :email, email: true
end

app/models/country.rb
class Country < ActiveRecord::Base

  has_many :vicinities
  has_many :regions, through: :vicinities
  has_many :connections
  has_many :neighbors, through: :connections
  has_many :country_scores

  accepts_nested_attributes_for :vicinities
  accepts_nested_attributes_for :connections

end

app/models/country_score.rb
class CountryScore < ActiveRecord::Base

  belongs_to :country
  belongs_to :game

  validates :country_id, :game_id, presence: true

  def us_controlled?
    us = us_influence
    ussr = ussr_influence
    stability = country.stability
    us >= stability && us >= ussr + stability
  end

  def ussr_controlled?
    us = us_influence
    ussr = ussr_influence
    stability = country.stability
    ussr >= stability && ussr >= us + stability
  end

end

app/models/game.rb
class Game < ActiveRecord::Base

  belongs_to :player_us, class_name: "User", inverse_of: :us_games
  belongs_to :player_ussr, class_name: "User", inverse_of: :ussr_games

  has_many :country_scores, dependent: :destroy
  has_one :tracker, dependent: :destroy

  validates :player_us, :player_ussr, presence: true

  after_create :setup_new_game

  scope :user_is_participant, ->(user) { where("(player_us_id = ?) OR (player_ussr_id = ?)", user, user) }

  private

  def setup_new_game
    initialize_tracker
    initialize_country_scores
  end

  def initialize_tracker
    Tracker.create!(game: self)
  end

  def initialize_country_scores
    countries = Country.all
    countries.each do |country|
      CountryScore.create!(game: self, country: country)
    end
  end

end

app/models/region.rb
class Region < ActiveRecord::Base

  has_many :vicinities
  has_many :countries, through: :vicinities

end

app/models/tracker.rb
class Tracker < ActiveRecord::Base

  belongs_to :game
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :us_games, class_name: "Game", inverse_of: :player_us, foreign_key: "player_us_id"
  has_many :ussr_games, class_name: "Game", inverse_of: :player_ussr, foreign_key: "player_ussr_id"

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable, :rememberable, :async

  mount_uploader :profile_image, ProfileImageUploader

  before_save :ensure_authentication_token_is_present

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true

  def name
    [first_name, last_name].join(" ").strip
  end

  def super_admin?
    role == "super_admin"
  end

  def as_json(options={})
    new_options = options.merge(only: [:email, :first_name, :last_name, :current_sign_in_at])

    super new_options
  end

  def games
    Game.user_is_participant(self.id)
  end

  private

  def ensure_authentication_token_is_present
    if authentication_token.blank?
      self.authentication_token = generate_authentication_token
    end
  end

  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.where(authentication_token: token).first
    end
  end

end

app/models/vicinity.rb
class Vicinity < ActiveRecord::Base

  belongs_to :country
  belongs_to :region

end

app/controllers/games_controller.rb
class GamesController < InheritedResources::Base

  before_action :load_game, only: [:show, :edit, :update, :destroy]

  def index
    @games = current_user.games
  end

  def new
    @game = current_user.games.new
  end

  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: "Game was successfully created." }
        format.json { render action: "show", status: :created, location: @game }
      else
        format.html { flash.now[:danger] = "Please check your entry and try again."
                      render :new
                    }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    render
  end

  def edit
    render
  end

  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to game_path, notice: "Game was successfully updated." }
        format.json { head :no_content }
      else
        format.html { flash.now[:danger] = "Please check your entry and try again."
                      render :edit
                    }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private

  def load_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:player_us_id,
                                 :player_ussr_id,
                                 :status
                                )
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    render
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    render
  end

  def contact_us
    @contact = Contact.new
  end

  def about
    render
  end

end

app/controllers/regions_controller.rb
class RegionsController < InheritedResources::Base

  private

    def region_params
      params.require(:region).permit(:name, :abbr)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def super_admin_signed_in?
    user_signed_in? && current_user.super_admin?
  end

  def nav_link text, path, condition = false, options = {}
    class_name = (current_page?(path) || condition) ? 'active' : ''

    content_tag(:li, class: class_name) do
      options[:title] = text unless options.has_key?(:title)
      link_to text, path, options
    end
  end

end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/country_scores_helper.rb
module CountryScoresHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/trackers_helper.rb
module TrackersHelper
end

app/views/layouts/application.html+phone.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "TwilightStruggle"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    = stylesheet_link_tag "application_phone", media: "all"
    / <link rel="icon" href="/favicon.ico" type="image/x-icon">
    / <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  %body{class: "#{@layout_carrier.class_for_body}"}
    .navbar.navbar-default.navbar-static-top{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: "/"} TwilightStruggle
        .navbar-collapse.collapse
          = render 'shared/nav'
    .container
      .row
        .col-sm-12
          = bootstrap_flash
          = yield
    %footer
      / for footer
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application_phone"

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "TwilightStruggle"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    = stylesheet_link_tag "application_desktop", media: "all"
    / <link rel="icon" href="/favicon.ico" type="image/x-icon">
    / <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  %body{class: "#{@layout_carrier.class_for_body}"}
    .navbar.navbar-default.navbar-static-top{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: "/"} TwilightStruggle
        .navbar-collapse.collapse
          = render 'shared/nav'
    .container.page
      .row
        .col-sm-12
          = bootstrap_flash
          = yield
    %footer
      / for footer
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application_desktop"

app/views/layouts/superadmin.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Super Admin"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    = stylesheet_link_tag "application_desktop", media: "all"
    / <link rel="icon" href="/favicon.ico" type="image/x-icon">
    / <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  %body
    .navbar.navbar-default.navbar-static-top{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: "/"} TwilightStruggle
        .navbar-collapse.collapse
          = render "shared/superadmin_nav"
    .container
      .row
        .col-sm-12
          = bootstrap_flash
          = yield
    %footer
      / for footer
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application_desktop"

app/views/shared/_nav.html.haml
%ul.nav.navbar-nav
  = nav_link 'Home', root_path
  = nav_link 'About', pages_about_path
  = nav_link 'Contact us', pages_contact_us_path
= render('shared/user_right_nav')

app/views/shared/_superadmin_nav.html.haml
%ul.nav.navbar-nav
  = nav_link('Users', superadmin_users_path)
  = nav_link("Active Admin", active_admin_root_path)
  = nav_link('DJ', '/delayed_job', false, "target" => '_blank')
= render('shared/user_right_nav')

app/views/shared/_user_is_signed_in.html.haml
%li.dropdown
  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
    = current_user.name
    %b.caret
  %ul.dropdown-menu
    - if super_admin_signed_in?
      = nav_link 'Superadmin', superadmin_root_path
      %li.divider
    = nav_link 'My account', profile_path
    = nav_link 'Change password', password_edit_path
    = nav_link 'Logout', destroy_user_session_path, false, method: :delete

app/views/shared/_user_right_nav.html.haml
%ul.nav.navbar-nav.navbar-right
  - if user_signed_in?
    = render 'shared/user_is_signed_in'
  - else
    = nav_link 'Sign in', new_session_path(:user)