config/routes.rb
TwilightStruggle::Application.routes.draw do

  resources :trackers

  resources :country_scores

  resources :games

  resources :regions

  resources :countries

  devise_for :users, controllers: { registrations: 'registrations' }

  devise_scope :user do
    get '/login' => 'devise/sessions#new', as: :login
    get '/logout' => 'sessions#destroy', :as => :logout
    get '/signup' => 'registrations#new', :as => :signup
    scope 'my' do
      get 'profile', to: 'registrations#edit'
      put 'profile/update', to: 'registrations#update'
      get 'password/edit', to: 'registrations#edit_password'
      put 'password/update', to: 'registrations#update_password'
    end
  end

  unauthenticated do
    get '/logout' => redirect('/')
  end

  authenticate :user, ->(u) { u.super_admin? } do
    get '/delayed_job' => DelayedJobWeb, :anchor => false
    put '/delayed_job' => DelayedJobWeb, :anchor => false
    post '/delayed_job' => DelayedJobWeb, :anchor => false

    ActiveAdmin.routes(self)
    namespace :superadmin do
      root to: 'users#index'
      resources :users
    end

  end

  get 'pages/about'
  get 'pages/contact_us'
  resources :contacts, only: [:create]

  authenticated :user do
    get '/pages' => 'pages#index', as: :pages
  end

  unauthenticated do
    as :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_scope :user do
        post 'login' => 'sessions#create', as: 'login'
      end

      resources :users, only: [:show, :create, :update, :destroy], constraints: { id: /.*/ }
    end
  end

  root 'home#index'
end

app/models/country_score.rb
class CountryScore < ActiveRecord::Base

  belongs_to :country
  belongs_to :game

  validates :country_id, :game_id, presence: true

  def us_controlled?
    us = us_influence
    ussr = ussr_influence
    stability = country.stability
    us >= stability && us >= ussr + stability
  end

  def ussr_controlled?
    us = us_influence
    ussr = ussr_influence
    stability = country.stability
    ussr >= stability && ussr >= us + stability
  end

end

app/controllers/country_scores_controller.rb
class CountryScoresController < InheritedResources::Base

  before_action :load_country_score, only: [:show, :edit, :update, :destroy]

  def index
    @country_scores = CountryScore.all
  end

  def new
    @country_score = CountryScore.new
  end

  # def create
  #   @country_score = CountryScore.new(country_score_params)

  #   respond_to do |format|
  #     if @country_score.save
  #       format.html { redirect_to @country_score, notice: "Country score was successfully created." }
  #       format.json { render action: "show", status: :created, location: @country_score }
  #     else
  #       format.html { flash.now[:danger] = "Please check your entry and try again."
  #                     render :new
  #                   }
  #       format.json { render json: @country_score.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  def show
    render
  end

  def edit
    render
  end

  # def update
  #   respond_to do |format|
  #     if @country_score.update(country_score_params)
  #       format.html { redirect_to @country_score, notice: "Country score was successfully updated." }
  #       format.json { head :no_content }
  #     else
  #       format.html { flash.now[:danger] = "Please check your entry and try again."
  #                     render :edit
  #                   }
  #       format.json { render json: @country_score.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  def destroy
    @country_score.destroy
    respond_to do |format|
      format.html { redirect_to country_scores_url }
      format.json { head :no_content }
    end
  end

  private

  def load_country_score
    @country_score = CountryScore.find(params[:id])
  end

  def country_score_params
    params.require(:country_score).permit(:us_influence,
                                          :ussr_influence,
                                          :country_id,
                                          :game_id,
                                          :controlled_by
                                         )
  end

end

app/helpers/country_scores_helper.rb
module CountryScoresHelper
end

app/views/country_scores/_form.html.haml
= form_for @country_score do |f|
  - if @country_score.errors.any?
    #error_explanation
      %h2= "#{pluralize(@country_score.errors.count, "error")} prohibited this country_score from being saved:"
      %ul
        - @country_score.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :us_influence
    = f.number_field :us_influence
  .field
    = f.label :ussr_influence
    = f.number_field :ussr_influence
  .field
    = f.label :country
    = f.text_field :country
  .field
    = f.label :game
    = f.text_field :game
  .actions
    = f.submit 'Save'

app/views/country_scores/edit.html.haml
%h1 Editing country_score

= render 'form'

= link_to 'Show', @country_score
\|
= link_to 'Back', country_scores_path

app/views/country_scores/index.html.haml
%h1 Listing country_scores

%table
  %thead
    %tr
      %th Us influence
      %th Ussr influence
      %th Country
      %th Game
      %th
      %th
      %th
      
  %tbody
    - @country_scores.each do |country_score|
      %tr
        %td= country_score.us_influence
        %td= country_score.ussr_influence
        %td= country_score.country
        %td= country_score.game
        %td= link_to 'Show', country_score
        %td= link_to 'Edit', edit_country_score_path(country_score)
        %td= link_to 'Destroy', country_score, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Country score', new_country_score_path

app/views/country_scores/new.html.haml
%h1 New country_score

= render 'form'

= link_to 'Back', country_scores_path

app/views/country_scores/show.html.haml
%p#notice= notice

%p
  %b Us influence:
  = @country_score.us_influence
%p
  %b Ussr influence:
  = @country_score.ussr_influence
%p
  %b Country:
  = @country_score.country
%p
  %b Game:
  = @country_score.game

= link_to 'Edit', edit_country_score_path(@country_score)
\|
= link_to 'Back', country_scores_path