config/routes.rb
TwilightStruggle::Application.routes.draw do

  resources :trackers

  resources :country_scores

  resources :games

  resources :regions

  resources :countries

  devise_for :users, controllers: { registrations: 'registrations' }

  devise_scope :user do
    get '/login' => 'devise/sessions#new', as: :login
    get '/logout' => 'sessions#destroy', :as => :logout
    get '/signup' => 'registrations#new', :as => :signup
    scope 'my' do
      get 'profile', to: 'registrations#edit'
      put 'profile/update', to: 'registrations#update'
      get 'password/edit', to: 'registrations#edit_password'
      put 'password/update', to: 'registrations#update_password'
    end
  end

  unauthenticated do
    get '/logout' => redirect('/')
  end

  authenticate :user, ->(u) { u.super_admin? } do
    get '/delayed_job' => DelayedJobWeb, :anchor => false
    put '/delayed_job' => DelayedJobWeb, :anchor => false
    post '/delayed_job' => DelayedJobWeb, :anchor => false

    ActiveAdmin.routes(self)
    namespace :superadmin do
      root to: 'users#index'
      resources :users
    end

  end

  get 'pages/about'
  get 'pages/contact_us'
  resources :contacts, only: [:create]

  authenticated :user do
    get '/pages' => 'pages#index', as: :pages
  end

  unauthenticated do
    as :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_scope :user do
        post 'login' => 'sessions#create', as: 'login'
      end

      resources :users, only: [:show, :create, :update, :destroy], constraints: { id: /.*/ }
    end
  end

  root 'home#index'
end

app/models/region.rb
class Region < ActiveRecord::Base

  has_many :vicinities
  has_many :countries, through: :vicinities

end

app/controllers/regions_controller.rb
class RegionsController < InheritedResources::Base

  private

    def region_params
      params.require(:region).permit(:name, :abbr)
    end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/regions/_form.html.haml
= form_for @region do |f|
  - if @region.errors.any?
    #error_explanation
      %h2= "#{pluralize(@region.errors.count, "error")} prohibited this region from being saved:"
      %ul
        - @region.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :abbr
    = f.text_field :abbr
  .actions
    = f.submit 'Save'

app/views/regions/edit.html.haml
%h1 Editing region

= render 'form'

= link_to 'Show', @region
\|
= link_to 'Back', regions_path

app/views/regions/index.html.haml
%h1 Listing regions

%table
  %thead
    %tr
      %th Name
      %th Abbr
      %th
      %th
      %th
      
  %tbody
    - @regions.each do |region|
      %tr
        %td= region.name
        %td= region.abbr
        %td= link_to 'Show', region
        %td= link_to 'Edit', edit_region_path(region)
        %td= link_to 'Destroy', region, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Region', new_region_path

app/views/regions/new.html.haml
%h1 New region

= render 'form'

= link_to 'Back', regions_path

app/views/regions/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @region.name
%p
  %b Abbr:
  = @region.abbr

= link_to 'Edit', edit_region_path(@region)
\|
= link_to 'Back', regions_path